Running on nodes: lrdn0001
Arguments passed: 100 1
/leonardo/home/userexternal/cditulli/thesis
total 184
drwxr-xr-x  2 cditulli interactive  4096 Jun 16 15:50 checkpoints
-rw-r--r--  1 cditulli interactive    47 Jun 12 15:53 clip_download.py
drwxr-xr-x 12 cditulli interactive  4096 Jun 16 15:40 logs
-rw-r--r--  1 cditulli interactive     8 Jun 11 17:57 README.md
-rw-r--r--  1 cditulli interactive   237 Jun 15 19:03 requirements.txt
drwxr-xr-x  2 cditulli interactive  4096 Jun 16 16:33 sout
drwxr-xr-x 12 cditulli interactive  4096 Jun 16 15:40 tb_logs
-rw-r--r--  1 cditulli interactive   701 Jun 14 14:31 training1.sh
-rw-r--r--  1 cditulli interactive   701 Jun 14 14:31 training2.sh
-rw-r--r--  1 cditulli interactive 12405 Jun 14 15:20 training_clip1_original.py
-rw-r--r--  1 cditulli interactive 12529 Jun 14 15:20 training_clip2_original.py
-rw-r--r--  1 cditulli interactive  9609 Jun 14 12:30 training_clip_msi1.py
-rw-r--r--  1 cditulli interactive 12141 Jun 14 12:30 training_clip_msi2.py
-rw-r--r--  1 cditulli interactive 20643 Jun 16 12:13 training_geobench_brick.py
-rw-r--r--  1 cditulli interactive 19230 Jun 16 16:18 training_geobench_eurosat.py
-rw-r--r--  1 cditulli interactive 21266 Jun 16 15:26 training_geobench_forestnet.py
-rw-r--r--  1 cditulli interactive 20457 Jun 16 12:21 training_geobench_pv4ger.py
-rw-r--r--  1 cditulli interactive  1132 Jun 16 16:18 training_geobench.sh
Traceback (most recent call last):
  File "/leonardo/prod/spack/5.2/install/0.21/linux-rhel8-icelake/gcc-8.5.0/anaconda3-2023.09-0-zcre7pfofz45c3btxpdk5zvcicdq5evx/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

Splits:
['train', 'valid', 'test']
2000 1000 1000

TEST set: -------------------------------------------------------------
   image_id  ...                  label
0  id_22869  ...  Herbaceous Vegetation
1  id_26790  ...           Sea and Lake
2  id_24810  ...         Permanent Crop
3  id_23442  ...                Highway
4  id_26899  ...           Sea and Lake

[5 rows x 6 columns]

VALIDATION set: -------------------------------------------------------
   image_id  ...                  label
0  id_18620  ...   Industrial Buildings
1  id_16798  ...            Annual Crop
2  id_18974  ...   Industrial Buildings
3  id_17806  ...  Herbaceous Vegetation
4  id_19661  ...         Permanent Crop

[5 rows x 6 columns]

TRAIN set: ------------------------------------------------------------
   image_id  ...                  label
0  id_12886  ...  Residential Buildings
1   id_3534  ...                 Forest
2   id_4735  ...  Herbaceous Vegetation
3   id_4354  ...  Herbaceous Vegetation
4   id_1175  ...            Annual Crop

[5 rows x 6 columns]
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18620.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18620.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16798.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16798.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18974.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18974.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17806.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17806.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19661.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19661.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18935.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18935.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18505.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18505.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18930.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18930.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19463.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19463.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21444.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21444.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20024.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20024.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18187.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18187.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21451.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21451.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16528.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16528.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20224.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20224.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17695.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17695.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17732.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17732.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19501.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19501.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16747.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16747.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20011.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20011.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19386.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19386.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16550.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16550.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19700.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19700.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17147.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17147.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19209.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19209.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18929.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18929.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19644.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19644.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19692.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19692.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16325.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16325.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20946.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20946.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19151.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19151.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21284.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21284.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20547.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20547.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16455.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16455.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20416.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20416.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17064.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17064.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17396.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17396.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17382.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17382.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18129.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18129.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17940.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17940.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18988.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18988.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21052.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21052.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17485.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17485.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20051.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20051.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19726.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19726.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17449.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17449.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19593.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19593.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20182.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20182.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19047.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19047.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20412.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20412.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20807.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20807.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20736.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20736.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18492.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18492.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17487.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17487.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20104.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20104.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20328.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20328.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18574.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18574.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20530.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20530.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19405.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19405.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18991.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18991.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17177.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17177.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21071.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21071.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17559.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17559.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21442.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21442.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21520.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21520.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16823.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16823.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20852.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20852.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19760.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19760.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18750.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18750.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16784.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16784.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19926.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19926.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20324.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20324.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17606.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17606.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21009.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21009.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16488.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16488.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16242.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16242.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18928.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18928.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19789.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19789.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19783.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19783.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18139.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18139.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20631.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20631.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21146.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21146.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18976.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18976.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19574.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19574.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20288.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20288.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16476.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16476.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19781.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19781.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17801.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17801.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18585.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18585.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21017.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21017.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16863.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16863.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19157.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19157.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16432.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16432.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20349.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20349.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19622.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19622.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17000.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17000.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17665.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17665.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19640.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19640.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16930.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16930.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21300.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21300.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18620.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18620.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16798.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16798.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18974.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18974.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17806.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17806.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19661.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19661.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18935.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18935.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18505.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18505.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18930.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18930.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19463.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19463.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21444.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21444.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20024.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20024.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18187.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18187.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21451.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21451.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16528.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16528.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20224.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20224.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17695.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17695.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17732.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17732.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19501.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19501.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16747.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16747.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20011.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20011.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19386.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19386.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16550.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16550.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19700.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19700.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17147.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17147.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19209.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19209.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18929.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18929.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19644.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19644.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19692.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19692.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16325.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16325.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20946.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20946.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19151.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19151.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21284.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21284.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20547.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20547.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16455.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16455.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20416.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20416.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17064.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17064.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17396.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17396.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17382.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17382.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18129.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18129.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17940.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17940.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18988.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18988.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21052.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21052.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17485.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17485.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20051.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20051.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19726.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19726.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17449.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17449.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19593.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19593.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20182.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20182.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19047.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19047.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20412.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20412.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20807.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20807.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20736.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20736.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18492.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18492.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17487.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17487.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20104.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20104.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20328.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20328.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18574.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18574.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20530.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20530.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19405.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19405.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18991.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18991.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17177.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17177.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21071.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21071.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17559.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17559.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21442.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21442.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21520.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21520.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16823.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16823.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20852.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20852.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19760.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19760.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18750.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18750.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16784.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16784.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19926.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19926.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20324.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20324.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17606.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17606.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21009.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21009.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16488.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16488.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16242.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16242.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18928.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18928.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19789.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19789.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19783.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19783.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18139.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18139.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20631.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20631.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21146.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21146.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18976.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18976.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19574.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19574.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20288.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20288.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16476.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16476.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19781.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19781.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17801.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17801.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A100-SXM-64GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type         | Params | Mode 
----------------------------------------------------
0 | clip_model | CLIP         | 151 M  | eval 
1 | embedder   | MSIEmbedder1 | 42     | train
----------------------------------------------------
42        Trainable params
151 M     Non-trainable params
151 M     Total params
605.109   Total estimated model params size (MB)
2         Modules in train mode
227       Modules in eval mode
SLURM auto-requeueing enabled. Setting signal handlers.
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18585.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18585.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21017.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21017.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16863.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16863.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19157.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19157.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16432.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16432.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20349.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_20349.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19622.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19622.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17000.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17000.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17665.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_17665.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19640.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_19640.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16930.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_16930.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Failed reading /content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21300.hdf5: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_21300.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
{'01 - Coastal aerosol': {'mean': nan, 'std': nan}, '02 - Blue': {'mean': nan, 'std': nan}, '03 - Green': {'mean': nan, 'std': nan}, '04 - Red': {'mean': nan, 'std': nan}, '05 - Vegetation Red Edge': {'mean': nan, 'std': nan}, '06 - Vegetation Red Edge': {'mean': nan, 'std': nan}, '07 - Vegetation Red Edge': {'mean': nan, 'std': nan}, '08 - NIR': {'mean': nan, 'std': nan}, '08A - Vegetation Red Edge': {'mean': nan, 'std': nan}, '09 - Water vapour': {'mean': nan, 'std': nan}, '10 - SWIR - Cirrus': {'mean': nan, 'std': nan}, '11 - SWIR': {'mean': nan, 'std': nan}, '12 - SWIR': {'mean': nan, 'std': nan}}
Traceback (most recent call last):
  File "/leonardo/home/userexternal/cditulli/thesis/training_geobench_eurosat.py", line 501, in <module>
    main()
  File "/leonardo/home/userexternal/cditulli/thesis/training_geobench_eurosat.py", line 491, in main
    trainer.fit(model, datamodule=data_module)
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1054, in _run_stage
    self._run_sanity_check()
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1083, in _run_sanity_check
    val_loop.run()
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 138, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 134, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 61, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/leonardo/home/userexternal/cditulli/thesis/training_geobench_eurosat.py", line 117, in __getitem__
    with h5py.File(img_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/h5py/_hl/files.py", line 564, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/leonardo/home/userexternal/cditulli/.conda/envs/test_env/lib/python3.11/site-packages/h5py/_hl/files.py", line 238, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 56, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 57, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/content/drive/MyDrive/Thesis CLIP4EO/GEO-Bench classification data/m-eurosat/id_18620.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Sanity Checking: |          | 0/? [00:00<?, ?it/s]                                                  srun: error: lrdn0001: task 0: Exited with exit code 1
